<a href="https://colab.research.google.com/github/it-programming-beginner/ml_beginner/blob/main/%E6%89%8B%E6%9B%B8%E3%81%8D%E7%94%BB%E5%83%8F%E8%AA%8D%E8%AD%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### データの準備

In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

digits = datasets.load_digits()

In [ ]:
x = digits.data # 画像データ
y = digits.target # 正解ラベル「0」～「9」

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=5, random_state=2)

In [ ]:
clf.fit(x_train, y_train) # 学習

RandomForestClassifier(n_estimators=5, random_state=2)

In [ ]:
predict = clf.predict(x_test) # 予測

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predict)) # 認識精度

0.8977777777777778


# 自作した手書き画像の認識

In [ ]:
from PIL import Image
import numpy as np

# 自作画像のフォーマットを変換
def pred(img_path):
  img = Image.open(img_path).convert('L')
  img.thumbnail((8, 8)) 
  img = np.array(img)
  img = img.flatten()
  return clf.predict([img])

In [ ]:
pred('3_1.png')

array([3])

In [ ]:
pred('3_.png')

array([1])

In [ ]:
pred('3.png')

array([3])

In [ ]:
pred('4.png')

array([4])

In [ ]:
pred('7.png')

array([7])

In [ ]:
pred('2.png')

array([2])